name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust based on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Replace with your actual build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist  # Adjust to your actual build output directory
