name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the website
        run: |
          # Install Node.js if you're using it
          npm install # or your build command if using a framework
          # Move to the root folder if needed
          mkdir output
          cp -r src/* output/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Specify the output directory containing index.html
